### ISSUE TITLE
Printing to stdout is not part of an algorithm for solving a problem.

### ISSUE THREAD

**Issue by alisafari1998** [sina-rostami/Reverse_costumizedGameOfLife#18]
https://github.com/sina-rostami/Reverse_costumizedGameOfLife/blob/e02161de570b8d2cbd389c5d921fec3e961229ff/Gol.cpp#L30

**Comment by sina-rostami** [comment]
so what should I do instead?

**Comment by alisafari1998** [comment]
Return your result to your caller.
