### ISSUE TITLE
Dont use pow when shift does the job.

### ISSUE THREAD

**Issue by IYP-Programer-Yeah** [sina-rostami/Reverse_costumizedGameOfLife#19]

**Comment by sina-rostami** [comment]
how about return a boolean in a function like has_next_world that shows that there is a next world to present or not?
and continue the for loop while has_next_world is true?

**Comment by IYP-Programer-Yeah** [comment]
This issue is about using std::pow as a means to calculate powers of 2. This task can be achieved by simple arithmetic shift operator.
Example:
```
1<<i; // This is the same as std::pow(2, i)
```

**Comment by sina-rostami** [comment]
okay thanks
