### ISSUE TITLE
The class name naming convention is not consistent over the project.

### ISSUE THREAD

**Issue by IYP-Programer-Yeah** [sina-rostami/Reverse_costumizedGameOfLife#24]
https://github.com/sina-rostami/Reverse_costumizedGameOfLife/blob/aea9085abd60e1b3320565632f62c0a42b0b90fb/Gol.cpp#L9

**Comment by sina-rostami** [comment]
how about "GameOfLife" ?

**Comment by sina-rostami** [comment]
is the naming convention ok now ?
