### ISSUE TITLE
Is this the behavior of unique pointer?

### ISSUE THREAD

**Issue by IYP-Programer-Yeah** [sina-rostami/Reverse_costumizedGameOfLife#30]
https://github.com/sina-rostami/Reverse_costumizedGameOfLife/blob/1df00a7e8654852c8861a4c69b53af3425197ac8/UniquePointer.cpp#L15

**Comment by sina-rostami** [comment]
no, the std::unique_ptr doesn't have this constructor...

**Comment by IYP-Programer-Yeah** [comment]
Ok then, what's the proper way of handling that?

**Comment by IYP-Programer-Yeah** [comment]
Removing your own definition of copy constructor does not mean that the compiler will not generate you one. You need to explicitly delete the copy construct to tell compiler not to generate you one. Same goes for copy assignment or any other automatically generated member functions.

**Comment by sina-rostami** [comment]
to make a copy of an unique pointer....
I think we should use the copy constructor of the type.
example : 

```c
unique_ptr<string> a(new string("test"));
unique_ptr<string> b(new string(*a));
```

**Comment by sina-rostami** [comment]
I removed the copy constructor from code and now when I try to compile code below  : 
```c
UniquePointer<string> a(new string("are"));
UniquePointer<string> b(a);
```
this error occurs(as for the std::unique_ptr's) : 


```
UniquePointer.cpp: In function ‘int main()’:
UniquePointer.cpp:79:28: error: use of deleted function ‘constexpr UniquePointer<std::__cxx11::basic_string<char> >::UniquePointer(const UniquePointer<std::__cxx11::basic_string<char> >&)’
   79 |   UniquePointer<string> b(a);
      |                            ^
UniquePointer.cpp:6:29: note: ‘constexpr UniquePointer<std::__cxx11::basic_string<char> >::UniquePointer(const UniquePointer<std::__cxx11::basic_string<char> >&)’ is implicitly declared as deleted because ‘UniquePointer<std::__cxx11::basic_string<char> >’ declares a move constructor or move assignment operator
    6 | template <typename T> class UniquePointer {
```

**Comment by IYP-Programer-Yeah** [comment]
That is the right behavior and interface of unique_ptr. Read about the unique_ptr.

**Comment by sina-rostami** [comment]
ok. is it okay in code now?

**Comment by IYP-Programer-Yeah** [comment]
unique_ptr is essentially a pointer, that is why the value of it's element does not effect its value. It's assignment operator is not deep, nor is its constness. Hence a copy would mean that the pointer would be copied not the element that is contained. With that said, a copy constructor would violate the uniqueness of the unique pointer, hence the copy constructor in unique_ptr is explicitly deleted. Same about its copy assignment.

**Comment by IYP-Programer-Yeah** [comment]
> ok. is it okay in code now?

No, explicitly delete copy assignment and constructor.

**Comment by sina-rostami** [comment]
> > ok. is it okay in code now?
> 
> No, explicitly delete copy assignment and constructor.

is the delete correct now ?
