### ISSUE TITLE
These member functions can operate on const instances, also lost more can be const in this code

### ISSUE THREAD

**Issue by IYP-Programer-Yeah** [sina-rostami/Reverse_costumizedGameOfLife#32]
https://github.com/sina-rostami/Reverse_costumizedGameOfLife/blob/1df00a7e8654852c8861a4c69b53af3425197ac8/UniquePointer.cpp#L74

**Comment by sina-rostami** [comment]
is there anything else to make const?

**Comment by IYP-Programer-Yeah** [comment]
Yes, try to find them all later.

**Comment by sina-rostami** [comment]
> Yes, try to find them all later.

I make to operate on const instances in functions which doesn't have assignments to the data members...

**Comment by IYP-Programer-Yeah** [comment]
Still some things that can be const, hint: function parameters
