### ISSUE TITLE
Not what you intend to do, also issue #25

### ISSUE THREAD

**Issue by IYP-Programer-Yeah** [sina-rostami/Reverse_costumizedGameOfLife#34]
https://github.com/sina-rostami/Reverse_costumizedGameOfLife/blob/3798176bf219ffa2ef5157c78c6a8adfba8c7bb9/Array2D.h#L13

**Comment by sina-rostami** [comment]
in case of vector, default constructor generates a size 0 vector.

**Comment by IYP-Programer-Yeah** [comment]
So keep consistent with that.

**Comment by IYP-Programer-Yeah** [comment]
Also you are using a wrong syntax, what is that code doing?

**Comment by IYP-Programer-Yeah** [comment]
Check the section regarding delegating constructors.
https://en.cppreference.com/w/cpp/language/constructor

**Comment by sina-rostami** [comment]
> Also you are using a wrong syntax, what is that code doing?

this code, you mean ? 
```c
Array2D() : height(0), width(0), arr_ptr( """  unique_ptr<T[]>() """ ){};
```
it makes an empty unique pointer.
it could be done by just calling :
```c
Array2D(0,0);
```
how about that?

**Comment by sina-rostami** [comment]
yes; this is the Delegating constructor...

**Comment by IYP-Programer-Yeah** [comment]
The comment was regarding the old implementation:
```
 Array2D() { Array2D(1, 1); }; 
```
 This is not the correct syntax for delegating constructors.

**Comment by sina-rostami** [comment]
I pushed the new one...
