### ISSUE TITLE
why is first world a pointer, and final world a ref?

### ISSUE THREAD

**Issue by IYP-Programer-Yeah** [sina-rostami/Reverse_costumizedGameOfLife#6]
https://github.com/sina-rostami/Reverse_costumizedGameOfLife/blob/a4ae151b6f2ff8f66ccf50c242969a8ba8c55436/Gal.cpp#L9

**Comment by sina-rostami** [comment]
I used to make both of them be references.
but it seems that references should be initialized in constructor.
so I changed the firstWorld to a pointer to avoid the error...
