### ISSUE TITLE
When should the ++ operator be overloaded? Is overloading for any use correct?

### ISSUE THREAD

**Issue by IYP-Programer-Yeah** [sina-rostami/Reverse_costumizedGameOfLife#7]
https://github.com/sina-rostami/Reverse_costumizedGameOfLife/blob/e02161de570b8d2cbd389c5d921fec3e961229ff/world.h#L77

**Comment by sina-rostami** [comment]
no not correct for any use. 
I think it's clean to overload for this use.
ok I do it in a function instead.
